"""Social Secretary data models — alerts, contacts, learning queue, and configuration.

These models define the persistent data structures for the Social Secretary
proactive processor. They are stored as JSON files (not UniversalMessages)
because they represent accumulating state, not in-flight messages.

COMPONENT OVERVIEW
------------------
SocialAlert        — a single flagged event for main to surface to the user
ContactEntry       — a person in the user's social world
LearningObservation — an open question for main to resolve in conversation
SocialSecretaryConfig — runtime config for the processor
AlertQueue         — container for pending alerts
ContactsStore      — container for the contacts knowledge base
LearningQueue      — container for open and resolved observations

SECURITY NOTES
--------------
- These models never contain API keys, credentials, or raw social media tokens.
- ``SocialAlert.raw_reference_id`` holds only a platform-specific post ID,
  not the full post content.
- All constrained string fields use ``Literal`` types so Pydantic rejects
  invalid values at the storage boundary, not at query time.
- ``SocialSecretaryConfig.cycle_interval_minutes`` is bounded to >= 15 to
  prevent runaway API usage.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, timezone
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Literal type aliases — constrained string enumerations
# ---------------------------------------------------------------------------

RelationshipStrength = Literal["strong", "moderate", "weak", "unknown"]

EventType = Literal[
    "birthday",
    "health_update",
    "life_event",
    "career_change",
    "engagement",
    "birth",
    "death",
    "anniversary",
    "post_mention",
]

Urgency = Literal["immediate", "next_interaction", "low"]

RecommendedAction = Literal["inform_user", "suggest_response", "log_only"]

RecommendedTiming = Literal[
    "immediate",
    "next_natural_interaction",
    "next_heartbeat",
    "when_relevant",
]

AttentionLevel = Literal["watch_closely", "normal", "low"]

ObservationPriority = Literal["blocking", "important", "curious"]

ObservationStatus = Literal["open", "in_progress", "resolved", "archived"]

SecurityProfile = Literal["observer", "interactive", "publisher"]


# ---------------------------------------------------------------------------
# Helper factories
# ---------------------------------------------------------------------------


def _alert_id() -> str:
    return f"social_alert_{uuid.uuid4().hex[:8]}"


def _obs_id() -> str:
    return f"obs_{uuid.uuid4().hex[:8]}"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# SocialAlert
# ---------------------------------------------------------------------------


class SocialAlert(BaseModel):
    """A single alert generated by the Social Secretary.

    Produced when a social media item passes the relevance threshold and is
    worth surfacing to the user.  The ``acknowledged`` flag is set by main
    after the alert has been mentioned in conversation.

    Security notes:
    - ``raw_reference_id`` is a platform post ID only — not the post content.
    - ``summary`` is LLM-generated from sanitised content; it never contains
      raw URLs or HTML.
    """

    id: str = Field(
        default_factory=_alert_id,
        description="Unique alert identifier: 'social_alert_{hex8}'",
    )
    source: str = Field(description="Social platform: 'facebook', 'twitter', 'instagram', etc.")
    person: str = Field(description="Display name of the person who posted or was mentioned")
    relationship_strength: RelationshipStrength = Field(
        description="How strong the user's relationship with this person is"
    )
    relationship_context: str = Field(
        description="Short description of the relationship context: 'college friend group', 'team member', etc."
    )
    event_type: EventType = Field(description="Category of social event detected")
    summary: str = Field(
        description="Brief human-readable summary of what happened (1-2 sentences)"
    )
    urgency: Urgency = Field(description="How urgently the user should be informed")
    recommended_action: RecommendedAction = Field(
        description="What action main should take: inform_user, suggest_response, or log_only"
    )
    recommended_timing: RecommendedTiming = Field(description="When main should surface this alert")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score (0.0–1.0) that this alert is genuinely relevant",
    )
    raw_reference_id: str = Field(
        description="Platform-specific post/item ID for user lookup (not the post content)"
    )
    created: datetime = Field(
        default_factory=_utcnow,
        description="UTC timestamp when this alert was generated",
    )
    acknowledged: bool = Field(
        default=False,
        description="Set to True when main has surfaced this alert to the user",
    )
    acknowledged_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when this alert was acknowledged",
    )


# ---------------------------------------------------------------------------
# ContactEntry
# ---------------------------------------------------------------------------


class ContactEntry(BaseModel):
    """Lightweight record of a person relevant to the user's social world.

    Built up over time as the Social Secretary observes posts and alerts.
    Security review is triggered on every write to prevent the contacts store
    from being used to exfiltrate or accumulate sensitive profiles.
    """

    name: str = Field(description="Display name of the person")
    relationship: str = Field(
        description="Relationship label: 'close friend', 'team member', 'acquaintance', etc."
    )
    context_learned: str = Field(
        description="How the Social Secretary first learned about this person"
    )
    relevant_details: dict[str, str] = Field(
        default_factory=dict,
        description="Key-value facts: 'birthday' → 'April 15', 'scheduling' → 'no evening meetings'",
    )
    source: str = Field(description="Platform or context where this person was first encountered")
    social_ids: dict[str, str] = Field(
        default_factory=dict,
        description="Platform → ID mapping: 'facebook' → 'fb_id_123'",
    )
    last_updated: datetime = Field(
        default_factory=_utcnow,
        description="UTC timestamp of last update",
    )
    attention_level: AttentionLevel = Field(
        default="normal",
        description="How closely the Social Secretary monitors this person",
    )
    notes: list[str] = Field(
        default_factory=list,
        description="Free-form agent observations about this person",
    )


# ---------------------------------------------------------------------------
# LearningObservation
# ---------------------------------------------------------------------------


class LearningObservation(BaseModel):
    """An observation the Social Secretary has logged for follow-up.

    Observations are open questions that main should resolve in conversation
    (e.g. "User mentioned they were going to the doctor — what was the outcome?").
    They move through: open → in_progress → resolved → archived.

    Security notes:
    - ``observed`` content is written by the LLM from sanitised social data.
    - ``relates_to="other_person"`` triggers elevated security review on write.
    """

    id: str = Field(
        default_factory=_obs_id,
        description="Unique observation identifier: 'obs_{hex8}'",
    )
    observed: str = Field(description="What was noticed or learned")
    source_session: str = Field(description="Session key where this was observed")
    source_date: date = Field(description="Calendar date when this was observed")
    priority: ObservationPriority = Field(
        description="Urgency: 'blocking', 'important', or 'curious'"
    )
    best_context: str = Field(
        description="When to raise this with the user: 'casual_conversation', 'heartbeat', 'next_interaction', 'when_relevant'"
    )
    blocks: Optional[str] = Field(
        default=None,
        description="Name of the task or project this observation blocks, if any",
    )
    status: ObservationStatus = Field(
        default="open",
        description="Lifecycle state: 'open', 'in_progress', 'resolved', 'archived'",
    )
    resolved_date: Optional[date] = Field(
        default=None,
        description="Calendar date when the observation was resolved",
    )
    resolution: Optional[str] = Field(
        default=None,
        description="What was learned when this observation was resolved",
    )
    relates_to: str = Field(
        description="'user' if about the owner, 'other_person' if about a contact"
    )
    purpose: str = Field(
        description="Why this is tracked: 'scheduling', 'social_obligation', 'collaboration', 'enrichment'"
    )


# ---------------------------------------------------------------------------
# SocialSecretaryConfig
# ---------------------------------------------------------------------------


class SocialSecretaryConfig(BaseModel):
    """Configuration for the Social Secretary proactive processor.

    Security notes:
    - ``cycle_interval_minutes >= 15`` is enforced to prevent runaway API usage.
    - ``security_profile`` controls the processor's permission scope.
    - ``connected_platforms`` lists MCP server IDs — no credentials.
    - ``max_post_length_chars`` caps content before LLM evaluation.
    """

    enabled: bool = Field(
        default=False,
        description="Whether the Social Secretary is active",
    )
    cycle_interval_minutes: int = Field(
        default=120,
        ge=15,
        description="How often the processor runs in minutes (minimum 15)",
    )
    active_hours_start: str = Field(
        default="07:00",
        description="Don't run before this local time (HH:MM)",
    )
    active_hours_end: str = Field(
        default="22:00",
        description="Don't run after this local time (HH:MM)",
    )
    model: str = Field(
        default="anthropic/claude-haiku-4.5",
        description="LLM model for routine scanning (cheap model preferred)",
    )
    escalation_model: str = Field(
        default="anthropic/claude-sonnet-4.5",
        description="LLM model for ambiguous evaluations",
    )
    max_alerts_per_cycle: int = Field(
        default=10,
        ge=1,
        description="Maximum alerts to generate per processing cycle",
    )
    security_profile: SecurityProfile = Field(
        default="observer",
        description="Permission scope: 'observer' (read-only), 'interactive', or 'publisher'",
    )
    connected_platforms: list[str] = Field(
        default_factory=list,
        description="MCP server IDs for social platforms: ['facebook-mcp', 'twitter-mcp']",
    )
    watch_event_types: list[str] = Field(
        default_factory=lambda: [
            "birthday",
            "health_update",
            "life_event",
            "career_change",
            "engagement",
            "birth",
            "death",
            "anniversary",
        ],
        description="Event types to watch for during feed evaluation",
    )
    max_post_length_chars: int = Field(
        default=2000,
        ge=100,
        description="Truncate posts beyond this length before LLM evaluation",
    )
    strip_urls: bool = Field(
        default=True,
        description="Remove URLs from post content before evaluation",
    )
    strip_mentions: bool = Field(
        default=False,
        description="Remove @mentions from post content before evaluation",
    )


# ---------------------------------------------------------------------------
# Container models
# ---------------------------------------------------------------------------


class AlertQueue(BaseModel):
    """Persistent container for pending social alerts.

    Serialised to ``{workspace}/social/alerts.json``.
    """

    alerts: list[SocialAlert] = Field(
        default_factory=list,
        description="All alerts, including acknowledged ones",
    )
    last_cycle: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp of the most recent processing cycle",
    )
    total_cycles_run: int = Field(
        default=0,
        ge=0,
        description="Total number of processing cycles completed",
    )


class ContactsStore(BaseModel):
    """Persistent container for the contacts knowledge base.

    Serialised to ``{workspace}/social/contacts.json``.
    """

    contacts: list[ContactEntry] = Field(
        default_factory=list,
        description="All known contacts",
    )
    last_updated: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp of last contacts update",
    )


class LearningQueue(BaseModel):
    """Persistent container for open and resolved learning observations.

    Active queue: ``{workspace}/social/learning/queue.json``
    Archive:      ``{workspace}/social/learning/resolved.json``
    """

    observations: list[LearningObservation] = Field(
        default_factory=list,
        description="Learning observations (use status field to filter open/resolved/archived)",
    )
