"""Human-in-the-loop approval system — Layer 9 of OpenRattler's security architecture.

When a tool is marked ``requires_approval=True``, execution must not proceed
until an authorised human (or future automated policy) explicitly approves or
denies it.  ``ApprovalManager`` is the broker: it accepts requests from
``ToolExecutor``, notifies a registered handler (e.g. ``CLIApprovalHandler``),
and waits for a resolution with a hard timeout.

FLOW
----
1. ``ToolExecutor`` builds an ``ApprovalRequest`` capturing the operation,
   arguments, action level, rationale, and independently-verified provenance
   (trust_level, agent_id, timestamp — not the agent's stated reason).
2. ``ToolExecutor`` calls ``ApprovalManager.request_approval(request)``.
3. ``ApprovalManager`` checks the dead-stop registry first.  If the operation
   is listed in ``DEAD_STOP_ACTIONS``, it raises ``DeadStopError`` immediately
   without contacting any handler.
4. If not a dead stop, the manager stores the request, fires the registered
   handler as a background task, then waits on a per-request ``asyncio.Event``.
5a. Handler calls ``ApprovalManager.resolve(approval_id, approved, decided_by)``
    within the timeout → the event is set → ``request_approval`` returns
    ``ApprovalResult(approved=True/False, ...)``.
5b. Timeout fires → ``request_approval`` auto-denies and returns
    ``ApprovalResult(approved=False, decided_by="system:timeout", ...)``.
6. ``ToolExecutor`` checks ``result.approved``.  If True, it calls
   ``approval_manager.consume_token(result.approval_token, result.token_expiry)``
   to validate the single-use token before executing.  If consume_token returns
   False (expired or replayed), execution is blocked.

SECURITY NOTES
--------------
- Fail-secure: timeout always results in denial, never in permission.
- Dead-stop check runs before any handler is called — no code path bypasses it.
- Provenance in ``ApprovalRequest`` is populated by the executor from the
  verified ``AgentConfig`` — never from data the agent itself supplies.
- Rationale is agent-supplied and displayed AFTER the action description so
  users read *what* before they read *why*.
- ``approval_token`` is single-use and time-bounded.  ``consume_token`` marks
  it as used; a second call with the same token returns False (replay blocked).
- Audit events are written for every request, resolution, dead-stop block, and
  token consumption so the full approval trail is reconstructible.
- ``CLIApprovalHandler`` offloads ``input()`` to a thread executor so it
  does not block the event loop.
- If ``resolve`` is called after a timeout has already decided the request,
  it silently no-ops (the race window is small but real on slow machines).
"""

from __future__ import annotations

import asyncio
import sys
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Callable, Coroutine, Optional

from pydantic import BaseModel, Field

from openrattler.models.audit import AuditEvent
from openrattler.security.action_levels import DEAD_STOP_ACTIONS, DeadStopError
from openrattler.storage.audit import AuditLog

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

# Default token lifetime: 5 minutes.  Tokens not consumed within this window
# are rejected by consume_token even if a human approved them.
_TOKEN_LIFETIME_SECONDS = 300


class ApprovalRequest(BaseModel):
    """Describes a pending approval gate.

    Security notes:
    - ``provenance`` is populated by the caller from independently-verified
      data (e.g. ``AgentConfig.trust_level``, not the agent's own claim).
    - ``rationale`` is the agent's stated reason; it is agent-supplied and
      must be displayed AFTER the action description in all handler UIs.
    - ``approval_token`` is a single-use UUID generated by the caller; it is
      validated by ``consume_token`` immediately before execution.
    - ``timeout_seconds`` is enforced by ``ApprovalManager``; the caller
      cannot extend it at resolution time.
    """

    approval_id: str = Field(description="Unique identifier for this approval request")
    operation: str = Field(description="Tool name or operation being approved")
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Tool arguments or contextual details about the operation",
    )
    requesting_agent: str = Field(description="agent_id of the agent requesting execution")
    session_key: str = Field(description="Session in which the operation was requested")
    provenance: dict[str, Any] = Field(
        description=(
            "Independently-verified request metadata: trust_level, agent_id, timestamp. "
            "Must not be derived from user or agent-supplied data."
        )
    )
    timestamp: datetime = Field(description="UTC timestamp when the request was created")
    timeout_seconds: int = Field(
        default=30,
        description="Seconds to wait for a human decision; approval is auto-denied after this",
    )
    # --- Fields added in piece 39.2 ---
    action_level: int = Field(
        default=5,
        description=(
            "Severity level of the action (1=most dangerous, 5=safest). "
            "Declared by the executor from the tool definition, not the agent."
        ),
    )
    rationale: Optional[str] = Field(
        default=None,
        description=(
            "Agent's stated reason for requesting this action.  Agent-supplied; "
            "must be displayed AFTER the action block in all handler UIs."
        ),
    )
    trace_id: Optional[str] = Field(
        default=None,
        description="Universal Message trace_id for cross-system correlation",
    )
    approval_token: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description=(
            "Single-use token generated by the executor at request time. "
            "Validated by consume_token immediately before tool execution."
        ),
    )
    token_expiry: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
        + timedelta(seconds=_TOKEN_LIFETIME_SECONDS),
        description="UTC datetime after which the approval_token is no longer valid",
    )


class ApprovalResult(BaseModel):
    """Outcome of an approval gate.

    Security notes:
    - ``approved=False`` means the operation must not proceed, regardless
      of whether denial came from a human or from a timeout.
    - ``decided_by`` distinguishes human decisions from automatic ones
      (``"system:timeout"`` for timeouts).
    - ``approval_token`` and ``token_expiry`` are passed through from the
      request so the executor can call ``consume_token`` before executing.
      They are ``None`` for denied or timed-out results.
    """

    approval_id: str = Field(description="Matches the ApprovalRequest.approval_id")
    approved: bool = Field(description="True only if a human explicitly approved")
    decided_by: str = Field(
        description=(
            "Identity of the decider: e.g. ``'cli:user'``, ``'system:timeout'``, "
            "or an agent_id for automated policies"
        )
    )
    timestamp: datetime = Field(description="UTC timestamp of the decision")
    # --- Fields added in piece 39.2 ---
    approval_token: Optional[str] = Field(
        default=None,
        description=(
            "The single-use token from the request.  Present only when approved=True "
            "so the executor can validate it before executing."
        ),
    )
    token_expiry: Optional[datetime] = Field(
        default=None,
        description="Expiry datetime for the approval_token.  None when approved=False.",
    )


# ---------------------------------------------------------------------------
# Handler type alias
# ---------------------------------------------------------------------------

#: Async callable signature for approval notification handlers.
#: Called with (request, manager) so the handler can call ``manager.resolve``.
ApprovalHandler = Callable[["ApprovalRequest", "ApprovalManager"], Coroutine[Any, Any, None]]


# ---------------------------------------------------------------------------
# ApprovalManager
# ---------------------------------------------------------------------------


class ApprovalManager:
    """Broker for human-in-the-loop approval gates.

    One ``ApprovalManager`` instance is shared across all tool executions
    that require approval.  It maintains a per-request ``asyncio.Event`` so
    ``request_approval`` can ``await`` the human decision without blocking
    the event loop.

    Args:
        audit_log:               Audit log for request and resolution events.
        default_timeout_seconds: How long to wait before auto-denying.
                                 Individual requests can specify a shorter
                                 timeout via ``ApprovalRequest.timeout_seconds``.

    Security notes:
    - Timeout always denies — never grants.
    - Dead-stop actions are rejected before any handler is called; no
      approval flow is triggered for them.
    - ``consume_token`` must be called by the executor before executing an
      approved action.  It is single-use: a second call with the same token
      returns False even if it hasn't expired (replay prevention).
    - ``resolve`` silently no-ops if the request has already been decided
      (timeout race prevention); it never silently grants a timed-out request.
    - ``list_pending`` returns a snapshot; callers cannot mutate the internal
      store through the returned list.
    """

    def __init__(self, audit_log: AuditLog, default_timeout_seconds: int = 30) -> None:
        self._audit = audit_log
        self.default_timeout_seconds = default_timeout_seconds
        # Keyed by approval_id
        self._pending: dict[str, ApprovalRequest] = {}
        self._events: dict[str, asyncio.Event] = {}
        self._results: dict[str, ApprovalResult] = {}
        # IDs that have already been decided (timeout or resolved); used to
        # make resolve() idempotent when a handler fires after a timeout.
        self._decided: set[str] = set()
        self._handler: Optional[ApprovalHandler] = None
        # Single-use token tracking.  Tokens are added here when consumed so
        # that a second consume_token call for the same token returns False.
        self._consumed_tokens: set[str] = set()

    # ------------------------------------------------------------------
    # Handler registration
    # ------------------------------------------------------------------

    def set_handler(self, handler: ApprovalHandler) -> None:
        """Register the notification handler for new approval requests.

        The handler is called as a background ``asyncio.Task`` with the
        ``ApprovalRequest`` and this manager.  It should eventually call
        ``self.resolve(...)`` to unblock the waiting coroutine.

        Args:
            handler: Async callable ``(request, manager) -> None``.
        """
        self._handler = handler

    # ------------------------------------------------------------------
    # Token consumption
    # ------------------------------------------------------------------

    def consume_token(self, token: str, expiry: datetime) -> bool:
        """Validate and consume a single-use approval token.

        Called by ``ToolExecutor`` immediately before executing an approved
        action.  Returns ``False`` (block execution) if the token has already
        been consumed (replay) or if it has expired.  Returns ``True`` and
        marks the token consumed if valid.

        Args:
            token:  The ``approval_token`` from ``ApprovalResult``.
            expiry: The ``token_expiry`` from ``ApprovalResult``.

        Returns:
            ``True`` if the token is valid and has now been consumed.
            ``False`` if the token is expired or has already been consumed.
        """
        now = datetime.now(timezone.utc)
        if token in self._consumed_tokens:
            # Replay attempt — already used.
            return False
        if now >= expiry:
            # Token has expired.
            return False
        self._consumed_tokens.add(token)
        return True

    # ------------------------------------------------------------------
    # Core approval flow
    # ------------------------------------------------------------------

    async def request_approval(self, request: ApprovalRequest) -> ApprovalResult:
        """Block until the request is approved, denied, or timed out.

        Performs a dead-stop check first — if ``request.operation`` is in
        ``DEAD_STOP_ACTIONS``, raises ``DeadStopError`` immediately without
        contacting any handler.

        For non-dead-stop requests, stores the request, fires the handler as
        a background task, then waits for resolution.  On timeout the request
        is auto-denied.

        Args:
            request: Fully-constructed ``ApprovalRequest``.

        Returns:
            ``ApprovalResult`` — ``approved=False`` on timeout or denial,
            ``approved=True`` only on explicit human approval.

        Raises:
            DeadStopError: If ``request.operation`` is in ``DEAD_STOP_ACTIONS``.
                           Audit event ``dead_stop_blocked`` is written before
                           raising so the attempt is always recorded.
        """
        # --- Dead-stop check (must run before anything else) ---
        if request.operation in DEAD_STOP_ACTIONS:
            await self._audit.log(
                AuditEvent(
                    event="dead_stop_blocked",
                    agent_id=request.requesting_agent,
                    session_key=request.session_key,
                    details={
                        "operation": request.operation,
                        "action_level": request.action_level,
                        "approval_id": request.approval_id,
                        "trace_id": request.trace_id,
                        "provenance": request.provenance,
                    },
                )
            )
            raise DeadStopError(request.operation)

        approval_id = request.approval_id
        event = asyncio.Event()
        self._pending[approval_id] = request
        self._events[approval_id] = event

        # Audit-log the incoming request, including the new 39.2 fields.
        await self._audit.log(
            AuditEvent(
                event="approval_requested",
                agent_id=request.requesting_agent,
                session_key=request.session_key,
                details={
                    "approval_id": approval_id,
                    "operation": request.operation,
                    "action_level": request.action_level,
                    "trace_id": request.trace_id,
                    "context": request.context,
                    "provenance": request.provenance,
                    "timeout_seconds": request.timeout_seconds,
                },
            )
        )

        # Notify the handler (non-blocking — it may prompt the user).
        if self._handler is not None:
            asyncio.create_task(self._handler(request, self))

        # Wait with a hard timeout.
        timeout = request.timeout_seconds
        try:
            await asyncio.wait_for(event.wait(), timeout=float(timeout))
        except asyncio.TimeoutError:
            result = ApprovalResult(
                approval_id=approval_id,
                approved=False,
                decided_by="system:timeout",
                timestamp=datetime.now(timezone.utc),
                # No token on denial — executor must not consume anything.
                approval_token=None,
                token_expiry=None,
            )
            self._results[approval_id] = result
            self._decided.add(approval_id)
            await self._audit.log(
                AuditEvent(
                    event="approval_resolved",
                    agent_id=request.requesting_agent,
                    session_key=request.session_key,
                    details={
                        "approval_id": approval_id,
                        "approved": False,
                        "decided_by": "system:timeout",
                        "action_level": request.action_level,
                    },
                )
            )

        # Extract result (must exist after event.wait() or timeout path).
        result = self._results[approval_id]

        # Clean up pending state; keep _decided for idempotency.
        self._pending.pop(approval_id, None)
        self._events.pop(approval_id, None)
        self._results.pop(approval_id, None)

        return result

    async def resolve(self, approval_id: str, approved: bool, decided_by: str) -> None:
        """Resolve a pending approval request.

        Called by a handler (e.g. ``CLIApprovalHandler``) once the user has
        made a decision.  Passes the request's ``approval_token`` and
        ``token_expiry`` through to the result so the executor can validate
        the token before executing.

        Args:
            approval_id: Matches ``ApprovalRequest.approval_id``.
            approved:    ``True`` if the operation is permitted.
            decided_by:  Identity string for the decider (e.g. ``"cli:user"``).

        Raises:
            ValueError: If *approval_id* is not currently pending.

        Security notes:
        - If the request was already decided (timeout race), this method
          silently no-ops rather than raising, because the handler task may
          legitimately fire after a very tight timeout.
        - Token is only passed through on approval; denied results get None.
        """
        if approval_id in self._decided:
            # Already resolved (e.g. timed out before handler responded).
            return

        if approval_id not in self._pending:
            raise ValueError(f"No pending approval for id {approval_id!r}")

        request = self._pending[approval_id]

        # Pass token through only when approved — no token on denial.
        result = ApprovalResult(
            approval_id=approval_id,
            approved=approved,
            decided_by=decided_by,
            timestamp=datetime.now(timezone.utc),
            approval_token=request.approval_token if approved else None,
            token_expiry=request.token_expiry if approved else None,
        )
        self._results[approval_id] = result
        self._decided.add(approval_id)

        await self._audit.log(
            AuditEvent(
                event="approval_resolved",
                agent_id=request.requesting_agent,
                session_key=request.session_key,
                details={
                    "approval_id": approval_id,
                    "approved": approved,
                    "decided_by": decided_by,
                    "action_level": request.action_level,
                },
            )
        )

        # Unblock the waiting request_approval coroutine.
        self._events[approval_id].set()

    async def list_pending(self) -> list[ApprovalRequest]:
        """Return a snapshot of all currently-pending approval requests.

        Returns a copy so callers cannot mutate the internal store.
        """
        return list(self._pending.values())


# ---------------------------------------------------------------------------
# CLIApprovalHandler
# ---------------------------------------------------------------------------


class CLIApprovalHandler:
    """Approval handler that prompts the CLI user for a y/n decision.

    Prints the request details (including provenance) to stdout and reads
    the response from stdin inside a thread executor so the event loop is
    not blocked.

    Usage::

        handler = CLIApprovalHandler()
        manager = ApprovalManager(audit_log)
        manager.set_handler(handler)

    Security notes:
    - Provenance is always printed so the user sees the independently-verified
      metadata, not just the agent's stated reason.
    - Rationale (agent-supplied) is printed AFTER the action block and
      separated by a divider so users read *what* before they read *why*.
    - An empty or unrecognised answer is treated as denial (fail-secure).
    - ``_read_input`` is a static method so tests can patch it without
      blocking on stdin.
    """

    async def __call__(self, request: ApprovalRequest, manager: ApprovalManager) -> None:
        """Print request details and resolve based on user input."""
        self._print_request(request)
        loop = asyncio.get_event_loop()
        answer: str = await loop.run_in_executor(None, self._read_input)
        approved = answer.strip().lower() in ("y", "yes")
        try:
            await manager.resolve(request.approval_id, approved, "cli:user")
        except ValueError:
            # Request already decided (timeout race) — nothing to do.
            pass

    @staticmethod
    def _print_request(request: ApprovalRequest) -> None:
        """Print the approval request summary to stdout.

        Action block is printed first, rationale block second — this ordering
        ensures users read *what* before the agent's *why* can influence them.
        """
        from openrattler.security.action_levels import ACTION_LEVEL_DESCRIPTIONS

        wide = "=" * 60
        thin = "-" * 60
        level_label = ACTION_LEVEL_DESCRIPTIONS.get(request.action_level, "Unknown")

        print(f"\n{wide}", file=sys.stdout)
        print("[APPROVAL REQUIRED]", file=sys.stdout)
        print(f"  Action  : {request.operation}", file=sys.stdout)
        print(f"  Level   : {request.action_level} — {level_label}", file=sys.stdout)
        print(f"  Agent   : {request.requesting_agent}", file=sys.stdout)
        print(f"  Session : {request.session_key}", file=sys.stdout)
        print(f"  Context : {request.context}", file=sys.stdout)
        print(f"  Timeout : {request.timeout_seconds}s", file=sys.stdout)
        print(f"{thin}", file=sys.stdout)

        rationale_text = (
            request.rationale if request.rationale is not None else "(no rationale provided)"
        )
        print("  Reason (agent's stated rationale):", file=sys.stdout)
        print(f"  {rationale_text!r}", file=sys.stdout)
        print(f"{wide}", file=sys.stdout)

    @staticmethod
    def _read_input() -> str:
        """Blocking stdin read — run inside a thread executor."""
        return input("Approve? [y/N]: ")


# ---------------------------------------------------------------------------
# ApprovalHandlerRouter
# ---------------------------------------------------------------------------


def _channel_from_session_key(session_key: str) -> str:
    """Extract the channel name from a session key.

    Session key format: ``agent:<agent_id>:<channel>[:<hash>]``.
    Examples:
      ``agent:main:slack:abc123`` → ``"slack"``
      ``agent:main:email:abc123`` → ``"email"``
      ``agent:main:main``         → ``"cli"``  (the literal "main" segment = CLI)
    """
    parts = session_key.split(":")
    if len(parts) >= 3:
        channel = parts[2]
        return channel if channel != "main" else "cli"
    return "cli"


class ApprovalHandlerRouter:
    """Dispatches approval requests to the appropriate channel handler.

    At construction time, the caller provides a ``preferred_channel`` name and
    a mapping of available handlers.  On each call the router first tries the
    channel encoded in the request's ``session_key`` (so an email conversation
    gets approval prompts via email, a Slack conversation via Slack).  If the
    originating channel has no handler, it falls back to ``preferred_channel``,
    then to ``CLIApprovalHandler`` so approval requests are never silently
    dropped.

    Conforms to the ``ApprovalHandler`` callable protocol:
    ``async (request: ApprovalRequest, manager: ApprovalManager) -> None``.

    Args:
        preferred_channel: Name of the channel to use when the originating
                           channel has no handler (e.g. ``"slack"`` or ``"cli"``).
        handlers:          Mapping of channel name → handler.  Only channels
                           listed here are available for dispatch.

    Security notes:
    - Falls back to ``CLIApprovalHandler`` if neither the originating channel
      nor the preferred channel is configured — the router never raises and
      never silently drops an approval request.
    - A compromised config that names a missing channel cannot suppress approvals;
      the CLI fallback always fires.

    Example::

        router = ApprovalHandlerRouter(
            preferred_channel="slack",
            handlers={
                "slack": SlackApprovalHandler(...),
                "email": EmailApprovalHandler(...),
            },
        )
        manager.set_handler(router)
    """

    def __init__(
        self,
        preferred_channel: str,
        handlers: dict[str, ApprovalHandler],
    ) -> None:
        self._preferred_channel = preferred_channel
        self._handlers = dict(handlers)
        # Pre-built CLI fallback — instantiated once, not on every call.
        self._cli_fallback: ApprovalHandler = CLIApprovalHandler()

    async def __call__(self, request: ApprovalRequest, manager: ApprovalManager) -> None:
        """Dispatch the request to the originating channel, then preferred, then CLI.

        Args:
            request: The pending approval request.
            manager: The ``ApprovalManager`` broker; the selected handler must
                     call ``manager.resolve()`` to unblock execution.
        """
        # Route to the channel the session originated from so the user receives
        # the approval prompt on the same channel they sent the message on.
        originating = _channel_from_session_key(request.session_key)
        handler = (
            self._handlers.get(originating)
            or self._handlers.get(self._preferred_channel)
            or self._cli_fallback
        )
        await handler(request, manager)
