"""File-backed storage for Social Secretary data structures.

Manages three JSON files:

  {base_dir}/alerts.json               → AlertQueue
  {base_dir}/contacts.json             → ContactsStore
  {base_dir}/learning/queue.json       → LearningQueue  (open/in-progress)
  {base_dir}/learning/resolved.json    → LearningQueue  (archived)

Write semantics
---------------
- **Atomic writes** via temp-file + ``Path.replace()`` — same pattern as
  ``MemoryStore``.  A crash mid-write never leaves a corrupt file.
- **All file I/O** is offloaded to ``asyncio.to_thread()`` so the event loop
  is never blocked.
- **Per-file asyncio Locks** prevent interleaved writes.

Security review
---------------
``upsert_contact`` and ``add_observation`` pass the candidate data through
``MemorySecurityAgent.review_memory_change`` if a security agent is configured.
Alert writes are **not** reviewed — they are generated by the Social Secretary
itself (not from external input) and are already sanitised before reaching here.

Security notes
--------------
- ``base_dir`` is validated at construction: ``..`` segments and characters
  outside the safe set are rejected to prevent path traversal.
- Audit events are written on every mutation so the forensic trail is
  complete regardless of whether the write was allowed or blocked.
- The session key used for security review is always
  ``agent:social_secretary:system`` — never derived from social media content.
"""

from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional

from openrattler.models.audit import AuditEvent
from openrattler.models.social import (
    AlertQueue,
    ContactEntry,
    ContactsStore,
    LearningObservation,
    LearningQueue,
    SocialAlert,
)

if TYPE_CHECKING:
    from openrattler.security.memory_security import MemorySecurityAgent
    from openrattler.storage.audit import AuditLog

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Session key used when the Social Secretary calls the security agent.
_SS_SESSION_KEY = "agent:social_secretary:system"

#: Agent ID passed to the security agent for review attribution.
_SS_AGENT_ID = "social_secretary"

#: Pattern for allowed characters in the base_dir path string.
_SAFE_PATH: re.Pattern[str] = re.compile(r"^[a-zA-Z0-9_./ :\\-]+$")


# ---------------------------------------------------------------------------
# Path validation
# ---------------------------------------------------------------------------


def _validate_base_dir(base_dir: Path) -> None:
    """Reject ``base_dir`` paths that could enable path traversal.

    Security notes:
    - ``..`` in any position is rejected — it is the primary path traversal
      vector regardless of platform.
    - Only alphanumeric characters, underscores, hyphens, dots, slashes,
      spaces, colons (Windows drive letters), and backslashes are allowed.
    - An empty path is rejected because it would resolve to the current
      working directory.
    """
    path_str = str(base_dir)
    if not path_str:
        raise ValueError("base_dir must not be empty")
    # Check for path traversal using resolved parts
    for part in Path(path_str).parts:
        if part == "..":
            raise ValueError(f"base_dir must not contain '..': {base_dir!r}")
    if not _SAFE_PATH.match(path_str):
        raise ValueError(f"base_dir contains non-standard characters: {base_dir!r}")


# ---------------------------------------------------------------------------
# Synchronous I/O helpers (run inside asyncio.to_thread)
# ---------------------------------------------------------------------------


def _sync_load_json(path: Path) -> dict[str, Any]:
    """Return the parsed JSON dict from *path*, or ``{}`` if not found."""
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)  # type: ignore[no-any-return]


def _sync_save_json(path: Path, data: dict[str, Any]) -> None:
    """Atomically write *data* to *path* via temp-file + rename.

    Security notes:
    - ``Path.replace()`` is used so the operation succeeds on Windows even
      when the target already exists.
    - The temp file is cleaned up on any exception before the rename so
      interrupted writes never leave stale ``.tmp`` files.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    try:
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, default=str, ensure_ascii=False)
            fh.flush()
        tmp.replace(path)
    except Exception:
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
        raise


# ---------------------------------------------------------------------------
# SocialStore
# ---------------------------------------------------------------------------


class SocialStore:
    """File-backed storage for Social Secretary alerts, contacts, and learning queue.

    Args:
        base_dir:       Root directory under which all social data files live.
                        Created on first write if it does not exist.
        security_agent: Optional ``MemorySecurityAgent`` that reviews contact
                        and observation writes before they are persisted.
        audit:          Optional ``AuditLog`` that receives mutation events.

    Security notes:
    - ``base_dir`` is validated at construction to prevent path traversal.
    - Alert writes bypass security review (SS-generated content).
    - Contact and observation writes are reviewed if a security agent is set.
    """

    def __init__(
        self,
        base_dir: Path,
        security_agent: Optional["MemorySecurityAgent"] = None,
        audit: Optional["AuditLog"] = None,
    ) -> None:
        _validate_base_dir(base_dir)
        self._base = base_dir
        self._security = security_agent
        self._audit = audit

        # Per-file asyncio Locks — one per managed file.
        self._alert_lock = asyncio.Lock()
        self._contact_lock = asyncio.Lock()
        self._queue_lock = asyncio.Lock()
        self._resolved_lock = asyncio.Lock()

    # ------------------------------------------------------------------
    # Path properties
    # ------------------------------------------------------------------

    @property
    def _alerts_path(self) -> Path:
        return self._base / "alerts.json"

    @property
    def _contacts_path(self) -> Path:
        return self._base / "contacts.json"

    @property
    def _queue_path(self) -> Path:
        return self._base / "learning" / "queue.json"

    @property
    def _resolved_path(self) -> Path:
        return self._base / "learning" / "resolved.json"

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _audit_event(self, event: str, **details: Any) -> None:
        """Emit an audit event if an audit log is configured."""
        if self._audit is None:
            return
        await self._audit.log(
            AuditEvent(
                event=event,
                agent_id=_SS_AGENT_ID,
                session_key=_SS_SESSION_KEY,
                details=dict(details),
            )
        )

    async def _security_review(self, content: dict[str, Any]) -> tuple[bool, Optional[str]]:
        """Run a security review on *content* if an agent is configured.

        Builds a minimal diff dict wrapping *content* as ``added`` entries and
        calls ``review_memory_change``.  Returns ``(allowed, reason)`` where
        ``allowed=True`` means the write can proceed.

        If no security agent is configured, always returns ``(True, None)``.
        """
        if self._security is None:
            return True, None
        diff: dict[str, Any] = {"added": content, "removed": {}, "modified": {}}
        result = await self._security.review_memory_change(_SS_AGENT_ID, diff, _SS_SESSION_KEY)
        if result.suspicious:
            return False, result.reason
        return True, None

    # ------------------------------------------------------------------
    # Alerts
    # ------------------------------------------------------------------

    async def load_alerts(self) -> AlertQueue:
        """Load the alert queue from disk, returning an empty queue if absent."""
        raw = await asyncio.to_thread(_sync_load_json, self._alerts_path)
        if not raw:
            return AlertQueue()
        return AlertQueue.model_validate(raw)

    async def save_alerts(self, queue: AlertQueue) -> None:
        """Atomically persist *queue* to disk."""
        async with self._alert_lock:
            await asyncio.to_thread(
                _sync_save_json,
                self._alerts_path,
                queue.model_dump(mode="json"),
            )

    async def add_alert(self, alert: SocialAlert) -> None:
        """Append *alert* to the queue and persist.

        Alert writes bypass security review — they originate from the Social
        Secretary's own evaluation pipeline, not from untrusted external input.
        """
        async with self._alert_lock:
            raw = await asyncio.to_thread(_sync_load_json, self._alerts_path)
            queue = AlertQueue.model_validate(raw) if raw else AlertQueue()
            queue.alerts.append(alert)
            queue.last_cycle = datetime.now(timezone.utc)
            await asyncio.to_thread(
                _sync_save_json,
                self._alerts_path,
                queue.model_dump(mode="json"),
            )
        await self._audit_event("social_alert_added", alert_id=alert.id, person=alert.person)

    async def acknowledge_alert(self, alert_id: str) -> bool:
        """Mark the alert with *alert_id* as acknowledged.

        Returns ``True`` if the alert was found and updated, ``False`` if not
        found.
        """
        async with self._alert_lock:
            raw = await asyncio.to_thread(_sync_load_json, self._alerts_path)
            queue = AlertQueue.model_validate(raw) if raw else AlertQueue()
            for i, alert in enumerate(queue.alerts):
                if alert.id == alert_id:
                    queue.alerts[i] = alert.model_copy(
                        update={
                            "acknowledged": True,
                            "acknowledged_at": datetime.now(timezone.utc),
                        }
                    )
                    await asyncio.to_thread(
                        _sync_save_json,
                        self._alerts_path,
                        queue.model_dump(mode="json"),
                    )
                    await self._audit_event("social_alert_acknowledged", alert_id=alert_id)
                    return True
        return False

    async def get_pending_alerts(self, max_urgency: Optional[str] = None) -> list[SocialAlert]:
        """Return unacknowledged alerts, optionally filtered by *max_urgency*.

        *max_urgency* selects alerts at or above the given urgency level
        in the order ``immediate > next_interaction > low``.  If ``None``,
        all unacknowledged alerts are returned.
        """
        queue = await self.load_alerts()
        pending = [a for a in queue.alerts if not a.acknowledged]
        if max_urgency is None:
            return pending
        _order = {"immediate": 0, "next_interaction": 1, "low": 2}
        threshold = _order.get(max_urgency, 2)
        return [a for a in pending if _order.get(a.urgency, 2) <= threshold]

    # ------------------------------------------------------------------
    # Contacts
    # ------------------------------------------------------------------

    async def load_contacts(self) -> ContactsStore:
        """Load the contacts store from disk, returning an empty store if absent."""
        raw = await asyncio.to_thread(_sync_load_json, self._contacts_path)
        if not raw:
            return ContactsStore()
        return ContactsStore.model_validate(raw)

    async def save_contacts(self, store: ContactsStore) -> None:
        """Atomically persist *store* to disk."""
        async with self._contact_lock:
            await asyncio.to_thread(
                _sync_save_json,
                self._contacts_path,
                store.model_dump(mode="json"),
            )

    async def upsert_contact(self, contact: ContactEntry) -> tuple[bool, Optional[str]]:
        """Insert or update a contact (matched by name, case-insensitive).

        Runs a security review on the contact data before writing.  Returns
        ``(True, None)`` on success or ``(False, reason)`` if the security
        agent blocks the write.
        """
        # Security review before any write.
        allowed, reason = await self._security_review(contact.model_dump(mode="json"))
        if not allowed:
            await self._audit_event(
                "contact_upserted",
                name=contact.name,
                blocked=True,
                reason=reason,
            )
            return False, reason

        async with self._contact_lock:
            raw = await asyncio.to_thread(_sync_load_json, self._contacts_path)
            store = ContactsStore.model_validate(raw) if raw else ContactsStore()
            name_lower = contact.name.lower()
            for i, existing in enumerate(store.contacts):
                if existing.name.lower() == name_lower:
                    store.contacts[i] = contact
                    break
            else:
                store.contacts.append(contact)
            store.last_updated = datetime.now(timezone.utc)
            await asyncio.to_thread(
                _sync_save_json,
                self._contacts_path,
                store.model_dump(mode="json"),
            )

        await self._audit_event("contact_upserted", name=contact.name, blocked=False)
        return True, None

    async def find_contact(self, name: str) -> Optional[ContactEntry]:
        """Find a contact by name (case-insensitive).  Returns ``None`` if not found."""
        store = await self.load_contacts()
        name_lower = name.lower()
        for contact in store.contacts:
            if contact.name.lower() == name_lower:
                return contact
        return None

    async def find_contacts_by_platform(
        self, platform: str, platform_id: str
    ) -> list[ContactEntry]:
        """Return all contacts whose ``social_ids[platform]`` matches *platform_id*."""
        store = await self.load_contacts()
        return [c for c in store.contacts if c.social_ids.get(platform) == platform_id]

    # ------------------------------------------------------------------
    # Learning Queue
    # ------------------------------------------------------------------

    async def load_learning_queue(self) -> LearningQueue:
        """Load the learning queue from disk, returning an empty queue if absent."""
        raw = await asyncio.to_thread(_sync_load_json, self._queue_path)
        if not raw:
            return LearningQueue()
        return LearningQueue.model_validate(raw)

    async def save_learning_queue(self, queue: LearningQueue) -> None:
        """Atomically persist the learning queue to disk."""
        async with self._queue_lock:
            await asyncio.to_thread(
                _sync_save_json,
                self._queue_path,
                queue.model_dump(mode="json"),
            )

    async def add_observation(self, obs: LearningObservation) -> tuple[bool, Optional[str]]:
        """Append *obs* to the learning queue after security review.

        Returns ``(True, None)`` on success or ``(False, reason)`` if blocked.
        """
        allowed, reason = await self._security_review(obs.model_dump(mode="json"))
        if not allowed:
            await self._audit_event(
                "observation_added",
                obs_id=obs.id,
                blocked=True,
                reason=reason,
            )
            return False, reason

        async with self._queue_lock:
            raw = await asyncio.to_thread(_sync_load_json, self._queue_path)
            queue = LearningQueue.model_validate(raw) if raw else LearningQueue()
            queue.observations.append(obs)
            await asyncio.to_thread(
                _sync_save_json,
                self._queue_path,
                queue.model_dump(mode="json"),
            )

        await self._audit_event("observation_added", obs_id=obs.id, blocked=False)
        return True, None

    async def resolve_observation(self, obs_id: str, resolution: str) -> bool:
        """Mark the observation with *obs_id* as resolved.

        Returns ``True`` if found and updated, ``False`` if not found.
        """
        from datetime import date

        async with self._queue_lock:
            raw = await asyncio.to_thread(_sync_load_json, self._queue_path)
            queue = LearningQueue.model_validate(raw) if raw else LearningQueue()
            for i, obs in enumerate(queue.observations):
                if obs.id == obs_id:
                    queue.observations[i] = obs.model_copy(
                        update={
                            "status": "resolved",
                            "resolved_date": date.today(),
                            "resolution": resolution,
                        }
                    )
                    await asyncio.to_thread(
                        _sync_save_json,
                        self._queue_path,
                        queue.model_dump(mode="json"),
                    )
                    await self._audit_event(
                        "observation_resolved", obs_id=obs_id, resolution=resolution
                    )
                    return True
        return False

    async def get_open_observations(
        self, priority: Optional[str] = None
    ) -> list[LearningObservation]:
        """Return observations with status ``"open"`` or ``"in_progress"``.

        If *priority* is given, further filters to that priority level only.
        """
        queue = await self.load_learning_queue()
        open_obs = [o for o in queue.observations if o.status in ("open", "in_progress")]
        if priority is not None:
            open_obs = [o for o in open_obs if o.priority == priority]
        return open_obs

    async def _read_resolved(self) -> LearningQueue:
        """Load the archived resolved observations from ``resolved.json``."""
        raw = await asyncio.to_thread(_sync_load_json, self._resolved_path)
        if not raw:
            return LearningQueue()
        return LearningQueue.model_validate(raw)

    async def archive_resolved(self) -> int:
        """Move all ``resolved`` observations to ``resolved.json`` and return the count.

        Resolved observations are changed to ``archived`` status as they are
        moved.  They are removed from ``queue.json``.

        Returns the number of observations archived in this call.
        """
        # Need both queue and resolved locks; acquire in a consistent order.
        async with self._queue_lock:
            async with self._resolved_lock:
                raw_queue = await asyncio.to_thread(_sync_load_json, self._queue_path)
                queue = LearningQueue.model_validate(raw_queue) if raw_queue else LearningQueue()

                to_archive = [o for o in queue.observations if o.status == "resolved"]
                remaining = [o for o in queue.observations if o.status != "resolved"]

                if not to_archive:
                    return 0

                archived = [o.model_copy(update={"status": "archived"}) for o in to_archive]

                raw_resolved = await asyncio.to_thread(_sync_load_json, self._resolved_path)
                resolved_store = (
                    LearningQueue.model_validate(raw_resolved) if raw_resolved else LearningQueue()
                )
                resolved_store.observations.extend(archived)

                # Write queue first, then resolved — if the second write fails,
                # the queue write will be retried on the next call.
                queue.observations = remaining
                await asyncio.to_thread(
                    _sync_save_json,
                    self._queue_path,
                    queue.model_dump(mode="json"),
                )
                await asyncio.to_thread(
                    _sync_save_json,
                    self._resolved_path,
                    resolved_store.model_dump(mode="json"),
                )

        count = len(archived)
        await self._audit_event("observations_archived", count=count)
        return count
